# site name
prefixName: Casuor
siteName:  
# favicon and site master avatar
favicon: https://cdn.jsdelivr.net/gh/Casuor/CDN/Image/favicon.ico
avatar: /Image/avatar.png
url: https://casuor.top
description: The wheel turns,nothing is ever new!
cdn: https://cdn.jsdelivr.net/gh/Casuor/CDN/
pjax: 1
# 1开启
mathjax: 0

notice: 欢迎参观小站!
lazyloadImg: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    技术: {path: /categories/Geek/, fa: fa-code }, 
    生活: {path: /categories/Live/, fa: fa-file-text-o }, 
    资源: {path: /categories/Resource/, fa: fa-cloud-download }, 
    随想: {path: /categories/Thinking/, fa: fa-commenting-o },
    转载: {path: /categories/Transfer/, fa: fa-book }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    书单: {path: /tags/Reading/, fa: fa-th-list faa-bounce }, 
    动漫: {path: /tags/Comic/, fa: fa-film faa-vertical }, 
    歌单: {path: /tags/Music/, fa: fa-headphones },
    图集: {path: /tags/Picture/, fa: fa-photo }
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/, fa: fa-link faa-shake }
  #赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about/, fa: fa-meetup}, 
    #主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
    Lab: {path: /lab/, fa: fa-cogs },
  } }
  #客户端: { path: /client/, fa: fa-android faa-vertical }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/Casuor/CDN/Image/Background/1.png
  - https://cdn.jsdelivr.net/gh/Casuor/CDN/Image/Background/2.png
  - https://cdn.jsdelivr.net/gh/Casuor/CDN/Image/Background/3.png
  - https://cdn.jsdelivr.net/gh/Casuor/CDN/Image/Background/4.png
  - https://cdn.jsdelivr.net/gh/Casuor/CDN/Image/Background/5.png
  - https://cdn.jsdelivr.net/gh/Casuor/CDN/Image/Background/6.png
  - https://cdn.jsdelivr.net/gh/Casuor/CDN/Image/Background/7.png
  - https://cdn.jsdelivr.net/gh/Casuor/CDN/Image/Background/8.png

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash: 
  - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: /Image/Startdash/hs1.png}
  - {url: https://space.bilibili.com/95683540, title: Bilibili, desc: 博主的b站视频, img: /Image/Startdash/hs2.png}
  - {url: /, title: Nothing, desc: 猪, img:  /Image/Startdash/hs3.png}



# your site build time or founded date
siteBuildingTime: 09/14/2017

#social  url, img PC端配置
social:
  github: {url: https://github.com/Casuor, img: /Image/Social/github.ico}
  sina: {url: http://j.mp/35ycJAK, img: /Image/Social/sina.ico}
  netease: {url: https://music.163.com/#/user/home?id=280651004, img: /Image/Social/neat.ico}
  zhihu: {url: https://www.zhihu.com/people/EyDBkb.io/activities, img: /Image/Social/zhihu.ico}
  telegram: {url: https://t.me/Eyestar, img: /Image/Social/Telegram.ico}
  #wechat: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}

#social  url, img 移动端配置
msocial:
  github: {url: https://github.com/Casuor, fa: fa-github, color: 333}
  weibo: {url: http://j.mp/35ycJAK, fa: fa-weibo, color: dd4b39}
  #qq: {url: https://wpa.qq.com/msgrd?v=3&uin=954655431&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  paypal: 
  alipay: #/Image/Donate/AliPayQR.jpg
  wechat: #/Image/Donate/WechatQR.png
  wechatSQ: #/Image/Donate/WechatQR.png

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/Casuor/CDN/Video
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: success.mp4

aplayer: 
  id: 3099159214
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: 88bwpzeLj6cM5Ih7CDJsUwzz-gzGzoHsz
v_appKey: L1bSPRMkKoL4w1KzkT85rXnl

